version: "3"
services:
 # mysql-database
  mysql-database:
    container_name: mysql-database
    image: mysql-database
    ports:
        - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adidas

  # Config-service
  config-service:
    container_name: config-service
    image: adidas/config-service:1.0.0
    expose:
      - "8888"

  # Eureka-server
  eureka-server:
    container_name: eureka-server
    image: adidas/eureka-server:1.0.0
    environment:
      SPRING_CONFIG_URI: "http://config-service:8888"
    ports:
      - "8761:8761"
  
# auth-service
  auth-service:
    container_name: auth-service
    image: adidas/auth-service:1.0.0
    environment:
      SPRING_CONFIG_URI: "http://config-service:8888"
    expose:
      - "8081"

  # gateway-service
  gateway-service:
    container_name: gateway-service
    image: adidas/gateway-service:1.0.0
    environment:
      SPRING_CONFIG_URI: "http://config-service:8888"
      AUTH_SERVER: "auth-service"
      AIRLINE_BUSINESS_SERVICE: "airline-business-service"
    ports:
      - "8080:8080"

  # airline-data-service
  airline-data-service:
    container_name: airline-data-service
    image: adidas/airline-data-service:1.0.0
    environment:
      SPRING_CONFIG_URI: "http://config-service:8888"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
      MYSQL_HOST: "mysql-database"
    expose:
      - "8090"
# airline-business-service
  airline-business-service:
    container_name: airline-business-service
    image: adidas/airline-business-service:1.0.0
    environment:
      SPRING_CONFIG_URI: "http://config-service:8888"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
    expose:
      - "8085"